# Théoreme central Limite

In [21]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from math import exp, sqrt, pi

In [16]:
domaine = range(-100 , 100)
mu = 0 # moyen
sigma = 0.1 #ecart type

# Notez l'utilisation du mot clé lambda. Il est très bien expliqué dans le cours
# "Apprenez à programmer en Python" sur OpenClassrooms.
f = lambda x : 1/(sqrt(2*pi*pow(sigma,2))) * exp(-pow((x-mu),2)/(2*pow(sigma,2)))

y = [f(x) for x in domaine]
plot = plt.plot(domaine, y)

In [24]:
vecteur_aleatoire = np.random.rand(30)
plt.scatter(range(30),vecteur_aleatoire)

In [25]:
matrice_aleatoire = np.random.rand(3,5)
matrice_aleatoire

array([[0.67138786, 0.37984422, 0.17298847, 0.11149166, 0.0956819 ],
       [0.32556165, 0.57790816, 0.03326139, 0.00978524, 0.30306469],
       [0.69402738, 0.37708038, 0.06635375, 0.08838536, 0.3729258 ]])

In [26]:
matrice = np.random.rand(100,200)
np.sum(matrice)
somme = np.sum(matrice,0)
somme.shape

(200,)

In [27]:
plt.scatter(range(200),somme)

In [28]:
plt.hist(somme)

(array([ 3.,  3., 13., 22., 36., 43., 42., 22., 11.,  5.]),
 array([41.63181258, 43.15842766, 44.68504275, 46.21165784, 47.73827293,
        49.26488802, 50.79150311, 52.3181182 , 53.84473329, 55.37134838,
        56.89796347]),
 <a list of 10 Patch objects>)

In [29]:
matrice = np.random.rand(1000,1000)
somme = np.sum(matrice , 0)
somme.shape
plot = plt.hist(somme, bins=100)