# NumPy

In [1]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [2]:
np.zeros(3)

array([0., 0., 0.])

In [3]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [4]:
np.full((5,4), 3.14)

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [5]:
x=np.full((10,20),4)

In [6]:
x.ndim

2

In [7]:
x.shape

(10, 20)

In [8]:
x.size

200

In [9]:
x.dtype

dtype('int32')

In [11]:
x[0,1]=3

In [12]:
x

array([[4, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]])

In [13]:
x[0,1]=3.14

In [14]:
x

array([[4, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]])

In [16]:
x = np.random.randint(10, size=6)

In [17]:
x

array([3, 4, 0, 6, 6, 6])

In [19]:

x[:2]

array([3, 4])

In [20]:
#dernier élément
x[-1]


6

In [21]:
# le pas de 2
x[::2]

array([3, 0, 6])

In [22]:
def calcule_inverse(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i]=1.0/values[i]
    return output

In [23]:
tableau_large = np.random.randint(1,10, size= 1000000)

In [24]:
%timeit calcule_inverse(tableau_large)

2.36 s ± 71.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [25]:
%timeit (1.0/tableau_large)

6.25 ms ± 220 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


# complement fonction universelles

In [26]:
# Il y a tout d'abord des opération mathématiques simples
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # Division avec arronid

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [27]:
x = [-2, -1, 1, 2]
print("La valeur absolue: ", np.abs(x))
print("Exponentielle: ", np.exp(x))
print("Logarithme: ", np.log(np.abs(x)))

La valeur absolue:  [2 1 1 2]
Exponentielle:  [0.13533528 0.36787944 2.71828183 7.3890561 ]
Logarithme:  [0.69314718 0.         0.         0.69314718]


# op Booléennes

In [44]:
x = np.random.rand(3,3)
print(x)
x > 0.5

[[0.79530901 0.48734743 0.08994328]
 [0.79114311 0.67066474 0.65548228]
 [0.29162519 0.75720764 0.83213685]]


array([[ True, False, False],
       [ True,  True,  True],
       [False,  True,  True]])

In [45]:
a=np.where(x > 0.5)

In [46]:
a

(array([0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 0, 1, 2, 1, 2], dtype=int64))

In [47]:
b=x[a]
b

array([0.79530901, 0.79114311, 0.67066474, 0.65548228, 0.75720764,
       0.83213685])

# Agrégation

In [52]:
L = np.random.random(100)
np.sum(L)

55.28831267813626

In [53]:
%timeit sum(tableau_large)
%timeit np.sum(tableau_large)

166 ms ± 3.81 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
447 µs ± 8.02 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [54]:
M = np.random.random((3, 4))
print(M)
# Notez la syntax variable.fonction au lieu de 
# np.fonction(variable). Les deux sont possibles si
# la variable est un tableau Numpy.
print("La somme de tous les éléments de M: ", M.sum())
print("Les sommes des colonnes de M: ", M.sum(axis=0))

[[0.95878263 0.82481653 0.12239718 0.33919195]
 [0.36718598 0.78302383 0.69300932 0.8665113 ]
 [0.99688479 0.22275194 0.19276827 0.42992906]]
La somme de tous les éléments de M:  6.797252772374363
Les sommes des colonnes de M:  [2.3228534  1.8305923  1.00817477 1.63563231]


# écart type
### Différence entre deux grandeurs ou valeurs (dont l'une est une moyenne ou une grandeur de référence).

In [55]:
np.std(tableau_large)

2.5822083087930756

In [56]:
# min -index de l'élément min
np.argmin(tableau_large)

2

In [58]:
tableau_large[2]

1

In [59]:
tableau_large

array([9, 8, 1, ..., 2, 6, 7])

In [63]:
np.percentile(tableau_large,10)

1.0